title: TanDonghua' Web
markdown: kramdown

# for atom feed
author:
  name: Sharad Raj Singh Maurya
  email: tandonghua_rock@163.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

categories:  
  - name: one  
    url: https://www.example1.com/  
  - name: two  
    url: https://www.example2.com/  


defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
